### ISSUE TITLE
Discord privileged Intents not granted

### ISSUE THREAD

**Issue by Stefouch** [Stefouch/sebedius-yearzero-discord-bot#61]
Discord's `GUILD_MEMBERS` & `GUILD_PRESENCES` privileged Intents are not granted. They aren't mandatory for the bot to work, but are useful for admin tasks.

**Todo:**
- [x] Temporary fix: disable these privileged intents
- [x] Get the bot **verified** by Discord
- [ ] Contact Discord support
- [ ] Solve the issue
- [ ] Re-enable these privileged intents and the admin commands
